---
name: concurrent search tests

on: [push, pull_request]

jobs:
  precommit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # precommit on ubuntu-latest is run as a part of the gradle-check workflow
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Build the repo
        run: |
          ./gradlew assemble -x :distribution:docker:buildArm64DockerImage -x :distribution:docker:buildDockerImage -x :distribution:docker:buildPpc64leDockerImage -x :distribution:docker:docker-export:exportDockerImage -x :distribution:docker:buildS390xDockerImage -x :distribution:docker:docker-ppc64le-export:exportDockerImage -x :distribution:docker:docker-s390x-export:exportDockerImage
      - name: Run Gradle integration tests
        run: |
          ./gradlew internalClusterTest -Dopensearch.experimental.feature.concurrent_segment_search.enabled=true
      - name: Upload Coverage Integration Test Report
        if: always()
        uses: codecov/codecov-action@v2
        with:
          files: ./build/reports/jacoco/test/integrationTestReport.xml
      - name: Run Gradle unit tests
        if: always()
        run: |
          ./gradlew test -Dopensearch.experimental.feature.concurrent_segment_search.enabled=true
      - name: Upload Coverage Unit Test Report
        if: always()
        uses: codecov/codecov-action@v2
        with:
          files: ./build/reports/jacoco/test/unitTestReport.xml
