---
name: concurrent search tests

on: [push, pull_request]

jobs:
  precommit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]  # precommit on ubuntu-latest is run as a part of the gradle-check workflow
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Build the repo
        run: |
          ./gradlew assemble
      - name: Run Gradle unit tests
        run: |
          ./gradlew test -Dopensearch.experimental.feature.concurrent_segment_search.enabled=true
      - name: Upload Coverage Unit Test Report
        uses: codecov/codecov-action@v2
        with:
          files: ./build/reports/jacoco/test/unitTestReport.xml
      - name: Run Gradle integration tests
        run: |
          ./gradlew internalClusterTest -Dopensearch.experimental.feature.concurrent_segment_search.enabled=true
      - name: Upload Coverage Integration Test Report
        uses: codecov/codecov-action@v2
        with:
          files: ./build/reports/jacoco/test/integrationTestReport.xml
