name: Sync Fork

on:
  schedule:
    - cron: '*/2 * * * *' # every 2 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: neetiks
          base: main
          head: main

